In [4]:
import numpy as np

In [5]:
print(dir())

['In', 'Out', '_', '_2', '__', '___', '__builtin__', '__builtins__', '__doc__', '__loader__', '__name__', '__package__', '__spec__', '_dh', '_i', '_i1', '_i2', '_i3', '_i4', '_i5', '_ih', '_ii', '_iii', '_oh', 'exit', 'get_ipython', 'np', 'quit']


In [2]:
# I want 4x4 numpy array whose all value set to True
np.full((4,4),fill_value=True)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [4]:
np.ones((4,4),dtype=bool)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [5]:
# I want 4x4 numpy array whose all value set to False
np.zeros((4,4),dtype=bool)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [7]:
# I want 4x4 numpy array whose diagonal value set to True and non diagonal False
np.identity(4,dtype=bool)

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [9]:
np.eye(4,dtype=bool)

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [ ]:
#Assignment: I want 4x4 numpy array whose diagonal value set to False and non diagonal True

# Check different properties of numpy array

In [10]:
a = np.random.random((4,4))
a

array([[0.04449577, 0.00797512, 0.03953419, 0.82632261],
       [0.10459743, 0.52350595, 0.15486459, 0.53727578],
       [0.62102901, 0.7862436 , 0.36283854, 0.81678047],
       [0.66890566, 0.9083547 , 0.76749782, 0.86331666]])

In [11]:
# size: total elements present
a.size

16

In [14]:
# check shape
a.shape

(4, 4)

In [15]:
print('Total number of rows',a.shape[0])
print('Total number of columns',a.shape[1])

Total number of rows 4
Total number of columns 4


In [16]:
# a memory in bytes to each element
a.itemsize

8

In [18]:
# check data type
a.dtype

dtype('float64')

In [19]:
# check a memory
a.data

In [20]:
#check dimension
a.ndim

2

# Shape manipulation

In [24]:
print(a)
print(a)
print('Ganesh')

[[0.04449577 0.00797512 0.03953419 0.82632261]
 [0.10459743 0.52350595 0.15486459 0.53727578]
 [0.62102901 0.7862436  0.36283854 0.81678047]
 [0.66890566 0.9083547  0.76749782 0.86331666]]
[[0.04449577 0.00797512 0.03953419 0.82632261]
 [0.10459743 0.52350595 0.15486459 0.53727578]
 [0.62102901 0.7862436  0.36283854 0.81678047]
 [0.66890566 0.9083547  0.76749782 0.86331666]]
Ganesh


In [25]:
display(a,a,'Ganesh')

array([[0.04449577, 0.00797512, 0.03953419, 0.82632261],
       [0.10459743, 0.52350595, 0.15486459, 0.53727578],
       [0.62102901, 0.7862436 , 0.36283854, 0.81678047],
       [0.66890566, 0.9083547 , 0.76749782, 0.86331666]])

array([[0.04449577, 0.00797512, 0.03953419, 0.82632261],
       [0.10459743, 0.52350595, 0.15486459, 0.53727578],
       [0.62102901, 0.7862436 , 0.36283854, 0.81678047],
       [0.66890566, 0.9083547 , 0.76749782, 0.86331666]])

'Ganesh'

In [26]:
#shape
a.shape

(4, 4)

In [ ]:
# 16 eleements: 
# 1,16
# 2,8
# 8,2
# 4,4
# 16,1
#---- 3D
"""
1,4,4
2,2,4
4,2,2
"""


## reshape():it changes shape temp.

In [28]:
# convert shape to 8(rows)x2(columns)
a.reshape(8,2)

array([[0.04449577, 0.00797512],
       [0.03953419, 0.82632261],
       [0.10459743, 0.52350595],
       [0.15486459, 0.53727578],
       [0.62102901, 0.7862436 ],
       [0.36283854, 0.81678047],
       [0.66890566, 0.9083547 ],
       [0.76749782, 0.86331666]])

In [29]:
#3D using reshape
# 2x4x2
a.reshape(2,4,2)

array([[[0.04449577, 0.00797512],
        [0.03953419, 0.82632261],
        [0.10459743, 0.52350595],
        [0.15486459, 0.53727578]],

       [[0.62102901, 0.7862436 ],
        [0.36283854, 0.81678047],
        [0.66890566, 0.9083547 ],
        [0.76749782, 0.86331666]]])

In [30]:
a # a is unchanged

array([[0.04449577, 0.00797512, 0.03953419, 0.82632261],
       [0.10459743, 0.52350595, 0.15486459, 0.53727578],
       [0.62102901, 0.7862436 , 0.36283854, 0.81678047],
       [0.66890566, 0.9083547 , 0.76749782, 0.86331666]])

## resize(): to do changes permanently

In [31]:
a

array([[0.04449577, 0.00797512, 0.03953419, 0.82632261],
       [0.10459743, 0.52350595, 0.15486459, 0.53727578],
       [0.62102901, 0.7862436 , 0.36283854, 0.81678047],
       [0.66890566, 0.9083547 , 0.76749782, 0.86331666]])

In [32]:
a.shape

(4, 4)

In [33]:
#convert into 1D permenantly
a.resize(16)

In [34]:
a

array([0.04449577, 0.00797512, 0.03953419, 0.82632261, 0.10459743,
       0.52350595, 0.15486459, 0.53727578, 0.62102901, 0.7862436 ,
       0.36283854, 0.81678047, 0.66890566, 0.9083547 , 0.76749782,
       0.86331666])

In [35]:
a.ndim

1

In [36]:
a.shape

(16,)

In [37]:
# lets change to 2D
a.resize((4,4))

In [38]:
a

array([[0.04449577, 0.00797512, 0.03953419, 0.82632261],
       [0.10459743, 0.52350595, 0.15486459, 0.53727578],
       [0.62102901, 0.7862436 , 0.36283854, 0.81678047],
       [0.66890566, 0.9083547 , 0.76749782, 0.86331666]])

In [39]:
a.shape

(4, 4)

In [40]:
# Convert to 3D
a.resize(4,2,2)

In [41]:
a

array([[[0.04449577, 0.00797512],
        [0.03953419, 0.82632261]],

       [[0.10459743, 0.52350595],
        [0.15486459, 0.53727578]],

       [[0.62102901, 0.7862436 ],
        [0.36283854, 0.81678047]],

       [[0.66890566, 0.9083547 ],
        [0.76749782, 0.86331666]]])

In [42]:
a.ndim

3

In [43]:
a.shape

(4, 2, 2)

In [44]:
a.shape

(4, 2, 2)

In [45]:
a

array([[[0.04449577, 0.00797512],
        [0.03953419, 0.82632261]],

       [[0.10459743, 0.52350595],
        [0.15486459, 0.53727578]],

       [[0.62102901, 0.7862436 ],
        [0.36283854, 0.81678047]],

       [[0.66890566, 0.9083547 ],
        [0.76749782, 0.86331666]]])

In [47]:
a.shape  = (2,8)

In [48]:
a

array([[0.04449577, 0.00797512, 0.03953419, 0.82632261, 0.10459743,
        0.52350595, 0.15486459, 0.53727578],
       [0.62102901, 0.7862436 , 0.36283854, 0.81678047, 0.66890566,
        0.9083547 , 0.76749782, 0.86331666]])

In [49]:
a.shape

(2, 8)

In [50]:
a.size

16

In [51]:
a.reshape(7,8)

ValueError: cannot reshape array of size 16 into shape (7,8)

In [58]:
x = np.array([1,2,3,4,5])
x

array([1, 2, 3, 4, 5])

In [59]:
x.dtype

dtype('int32')

In [60]:
x.__sizeof__()

124

In [61]:
y = np.array([1,2,3,4,5],dtype=object)
y

array([1, 2, 3, 4, 5], dtype=object)

In [62]:
y.__sizeof__()

144

## transpose: convert row to column and viceversa

In [52]:
a

array([[0.04449577, 0.00797512, 0.03953419, 0.82632261, 0.10459743,
        0.52350595, 0.15486459, 0.53727578],
       [0.62102901, 0.7862436 , 0.36283854, 0.81678047, 0.66890566,
        0.9083547 , 0.76749782, 0.86331666]])

In [53]:
a.shape

(2, 8)

In [54]:
a.transpose() #changes are temp.

array([[0.04449577, 0.62102901],
       [0.00797512, 0.7862436 ],
       [0.03953419, 0.36283854],
       [0.82632261, 0.81678047],
       [0.10459743, 0.66890566],
       [0.52350595, 0.9083547 ],
       [0.15486459, 0.76749782],
       [0.53727578, 0.86331666]])

In [55]:
a.T #transpose operation temp.

array([[0.04449577, 0.62102901],
       [0.00797512, 0.7862436 ],
       [0.03953419, 0.36283854],
       [0.82632261, 0.81678047],
       [0.10459743, 0.66890566],
       [0.52350595, 0.9083547 ],
       [0.15486459, 0.76749782],
       [0.53727578, 0.86331666]])

In [56]:
np.transpose(a)

array([[0.04449577, 0.62102901],
       [0.00797512, 0.7862436 ],
       [0.03953419, 0.36283854],
       [0.82632261, 0.81678047],
       [0.10459743, 0.66890566],
       [0.52350595, 0.9083547 ],
       [0.15486459, 0.76749782],
       [0.53727578, 0.86331666]])

In [57]:
a.shape #transpose changes

(2, 8)

In [64]:
nnp

NameError: name 'nnp' is not defined

# Indexing over numpy

In [ ]:
b = np.arange(1,25).reshape(6,4)
b

In [ ]:
# indexing in numpy works on rows
b[0]

In [ ]:
b[4]

In [ ]:
#access 11
b[2]

In [ ]:
b[2][2]

In [ ]:
b[2,2]

In [ ]:
#acess 20
b[4,3]

In [ ]:
#access 6
b[1,1]

In [ ]:
c = b.reshape(3,4,2)
c

In [ ]:
#access 12
c[1,1,1]

In [ ]:
#access 7
c[0,3,0]

In [ ]:
#access18
c[2,0,1]

# slicing

In [ ]:
b

In [ ]:
#slicing works on rows first


In [ ]:
#last 4 rows


In [ ]:
"""
[ 9, 10, 11, 12],
[13, 14, 15, 16],
"""


In [ ]:
"""
[ 1,  2,  3,  4]
[ 9, 10, 11, 12]
[17, 18, 19, 20]
"""


In [ ]:
#access first and last row


In [ ]:
# row 13 and 21
# Rule: If we want to skip one(n) row then step by 2(n+1)



In [ ]:
# row 21 13 5


In [ ]:
# b[row:column]
# b[row_index:column_index:step]
#b[::,::]

In [ ]:
b

In [ ]:
"""
10,11
14,15
"""


In [ ]:
#fetch corner elements
# 1,4,21,24


In [ ]:
#check shape

In [ ]:
# 19,20
# 23,24


In [ ]:
b

In [ ]:
#access middle 2 columns
b[:,1:3]

In [ ]:
b

In [ ]:
"""
[[ 1,  2,  3,  4],
[ 5,  6,  7,  8],
[13, 14, 15, 16],
[21, 22, 23, 24]]
"""