In [1]:
import numpy as np

In [2]:
a = np.arange(24).reshape(2,4,3)
a

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

In [3]:
np.split(a,2)

[array([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]]]),
 array([[[12, 13, 14],
         [15, 16, 17],
         [18, 19, 20],
         [21, 22, 23]]])]

In [5]:
np.split(a,3,axis=1)

ValueError: array split does not result in an equal division

## np.amax()

In [6]:
b = np.array([[2,30,1],[0,13,56],[70,3,5]])
b

array([[ 2, 30,  1],
       [ 0, 13, 56],
       [70,  3,  5]])

In [8]:
np.amax(b)

70

In [10]:
max(b.ravel())

70

In [11]:
# max element from columns
np.amax(b,axis=0)

array([70, 30, 56])

In [12]:
# # max element from rows
np.amax(b,axis=1)

array([30, 56, 70])

In [13]:
b

array([[ 2, 30,  1],
       [ 0, 13, 56],
       [70,  3,  5]])

## np.amin(): assignment

In [14]:
np.max(b)

70

In [15]:
np.max(b,axis=1)

array([30, 56, 70])

In [16]:
np.max(b,axis=0)

array([70, 30, 56])

### if i want to find out where max element of min element is present in an array then will use argmax, argmin

## np.argmax()

In [17]:
b

array([[ 2, 30,  1],
       [ 0, 13, 56],
       [70,  3,  5]])

In [19]:
b.ravel()

array([ 2, 30,  1,  0, 13, 56, 70,  3,  5])

In [21]:
b.ravel()[6]

70

In [18]:
np.argmax(b)

6

In [22]:
np.argmin(b)

3

In [23]:
# rowwise index of min element
np.argmin(b,axis=1)

array([2, 0, 1], dtype=int64)

In [24]:
b

array([[ 2, 30,  1],
       [ 0, 13, 56],
       [70,  3,  5]])

## np.concatenate

In [25]:
b

array([[ 2, 30,  1],
       [ 0, 13, 56],
       [70,  3,  5]])

In [32]:
c = np.array([[10,20,30]])
c

array([[10, 20, 30]])

In [33]:
# Rule: while performing a concatenation
# dimensions must match
np.concatenate((b,c))

array([[ 2, 30,  1],
       [ 0, 13, 56],
       [70,  3,  5],
       [10, 20, 30]])

In [37]:
d = np.array([[-1],
             [-2],
             [-3]])
d

array([[-1],
       [-2],
       [-3]])

In [34]:
b

array([[ 2, 30,  1],
       [ 0, 13, 56],
       [70,  3,  5]])

In [38]:
np.concatenate((b,d), axis=1)

array([[ 2, 30,  1, -1],
       [ 0, 13, 56, -2],
       [70,  3,  5, -3]])

In [ ]:
# LIC
#dept1 Sr. name age
#dept2 sr. name age
#dept3 sr. name age

#dept1 Sr. name age
#dept2 sr. Adhar Pan
#dept3 sr. BMI HR
#Sr. name age Ahdar Pan BMI HR


### What is difference between append and concatenate????

In [39]:
#np.delete()
a

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

In [40]:
# delete a from the memory
del a

In [41]:
a

NameError: name 'a' is not defined

In [42]:
s = 100
s

100

In [43]:
del s

In [44]:
s

NameError: name 's' is not defined

# Stastical operations over numpy array

## np.sum()

In [45]:
b

array([[ 2, 30,  1],
       [ 0, 13, 56],
       [70,  3,  5]])

In [46]:
# summation of all elements in b
np.sum(b)

180

In [49]:
# row wise summation
np.sum(b,axis=1)

array([33, 69, 78])

In [48]:
b

array([[ 2, 30,  1],
       [ 0, 13, 56],
       [70,  3,  5]])

In [50]:
# column wise summation
np.sum(b,axis=0)

array([72, 46, 62])

In [51]:
b

array([[ 2, 30,  1],
       [ 0, 13, 56],
       [70,  3,  5]])

In [52]:
sum(b)

array([72, 46, 62])

In [ ]:
np.mod()

In [53]:
1%5

1