In [1]:
import numpy as np

In [3]:
np.arange(1,25)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [4]:
np.arange(1,25).reshape(4,6) # row major

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [8]:
np.arange(1,25).reshape(4,6,order = 'F') #coloumn major

array([[ 1,  5,  9, 13, 17, 21],
       [ 2,  6, 10, 14, 18, 22],
       [ 3,  7, 11, 15, 19, 23],
       [ 4,  8, 12, 16, 20, 24]])

In [7]:
np.info('reshape')

     *** Found in numpy ***
 reshape(a, newshape, order='C')

Gives a new shape to an array without changing its data.

Parameters
----------
a : array_like
    Array to be reshaped.
newshape : int or tuple of ints
    The new shape should be compatible with the original shape. If
    an integer, then the result will be a 1-D array of that length.
    One shape dimension can be -1. In this case, the value is
    inferred from the length of the array and remaining dimensions.
order : {'C', 'F', 'A'}, optional
    Read the elements of `a` using this index order, and place the
    elements into the reshaped array using this index order.  'C'
    means to read / write the elements using C-like index order,
    with the last axis index changing fastest, back to the first
    axis index changing slowest. 'F' means to read / write the
    elements using Fortran-like index order, with the first index
    changing fastest, and the last index changing slowest. Note that
    the 'C' and 'F' optio

In [2]:
a = np.arange(1,25).reshape(4,6)
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [11]:
b = np.arange(1,25)
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [12]:
b.reshape(6,4,order='F')

array([[ 1,  7, 13, 19],
       [ 2,  8, 14, 20],
       [ 3,  9, 15, 21],
       [ 4, 10, 16, 22],
       [ 5, 11, 17, 23],
       [ 6, 12, 18, 24]])

In [13]:
b.reshape(6,4,order='C')

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [14]:
# b is unchanged
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [16]:
b = b.reshape(6,4,order='F')
b

array([[ 1,  7, 13, 19],
       [ 2,  8, 14, 20],
       [ 3,  9, 15, 21],
       [ 4, 10, 16, 22],
       [ 5, 11, 17, 23],
       [ 6, 12, 18, 24]])

## Conditional based selection

In [17]:
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [18]:
#fetch values >10
a > 10 
#performs elementwise operation
#it give u an array of boolean output 

array([[False, False, False, False, False, False],
       [False, False, False, False,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

In [19]:
#boolean indexing is supported
a[a > 10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [22]:
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [21]:
# Concept of Boolean indexing
# total 4 rows present in a
# indexing works on rows: and we are supplying boolean index
a[ [True,False,True,False] ]

array([[ 1,  2,  3,  4,  5,  6],
       [13, 14, 15, 16, 17, 18]])

In [23]:
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [24]:
# more than one condition we want to test
#fetch values divisible by 5 and 7
a % 5 == 0

array([[False, False, False, False,  True, False],
       [False, False, False,  True, False, False],
       [False, False,  True, False, False, False],
       [False,  True, False, False, False, False]])

In [25]:
a % 7 == 0

array([[False, False, False, False, False, False],
       [ True, False, False, False, False, False],
       [False,  True, False, False, False, False],
       [False, False,  True, False, False, False]])

In [ ]:
a

In [ ]:
#Logical: and or not
# bitwise: &(and) |(or) ~(not) ^(XOR)

In [26]:
(a % 5 == 0) | (a %7 == 0)

array([[False, False, False, False,  True, False],
       [ True, False, False,  True, False, False],
       [False,  True,  True, False, False, False],
       [False,  True,  True, False, False, False]])

In [29]:
a[(a % 5 == 0) | (a %7 == 0)]

array([ 5,  7, 10, 14, 15, 20, 21])

In [30]:
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [32]:
#fetch values divisible by 5 and 10
a[(a%5 ==0) & (a%10 == 0)]

array([10, 20])

In [ ]:
"""
XOR
00 0
01 1
10 1
11 0
"""

In [33]:
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [34]:
# Fetch values > 18
a > 18

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [ True,  True,  True,  True,  True,  True]])

In [38]:
a[a>18] 

array([19, 20, 21, 22, 23, 24])

### Can we compare 2 arrays?

In [43]:
x = np.array([[2,3],[4,5]])
x

array([[2, 3],
       [4, 5]])

In [44]:
y = np.array([[10,20],[6,7]])
y

array([[10, 20],
       [ 6,  7]])

In [48]:
x < y

array([[ True,  True],
       [ True,  True]])

In [50]:
x[x>y]

array([], dtype=int32)

In [51]:
y[x<y]

array([10, 20,  6,  7])

## Scalar mathematics over numpy array

In [52]:
x

array([[2, 3],
       [4, 5]])

In [53]:
# add 10 in each elemnt
x + 10
# result is temp

array([[12, 13],
       [14, 15]])

In [54]:
# assignment operator
x += 10
#changes persist in x , inplace operation

In [55]:
x

array([[12, 13],
       [14, 15]])

In [56]:
# using np add 100
np.add(x,100) #temp

array([[112, 113],
       [114, 115]])

In [58]:
# if u want to do the addition of x , y [ vector addition]
display(x,y)
x + y

array([[12, 13],
       [14, 15]])

array([[10, 20],
       [ 6,  7]])

array([[22, 33],
       [20, 22]])

In [59]:
np.add(x,y)

array([[22, 33],
       [20, 22]])

In [ ]:
# Assignment:x += y
# check wht happens

In [ ]:
np.power()

In [ ]:
# We want an array 4 X 4 in whcih all values must be True
np.full((4,4),True)

In [ ]:
np.ones((4,4),dtype='bool')

### We want an array 4 X 4 in whcih all values must be False

In [ ]:
np.full((4,4),False)

In [ ]:
np.zeros((4,4),dtype=bool)

### We want an array 4 X 4 in whcih diagonal values must be True and non diagonal False

In [ ]:
np.identity(4)

In [ ]:
np.identity(4,dtype=bool)

### We want an array 4 X 4 in whcih diagonal values must be False and non diagonal True

In [39]:
e = np.identity(4,dtype=int)
e

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [40]:
e2 = np.invert(e)
e2

array([[-2, -1, -1, -1],
       [-1, -2, -1, -1],
       [-1, -1, -2, -1],
       [-1, -1, -1, -2]], dtype=int32)

In [41]:
e2.astype('bool')

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [ ]:
e

In [42]:
~ e.astype('bool')

array([[False,  True,  True,  True],
       [ True, False,  True,  True],
       [ True,  True, False,  True],
       [ True,  True,  True, False]])

In [ ]:
e

In [ ]:
~ 1

In [ ]:
~ 0

In [ ]:
e

In [ ]:
e.dtype

In [ ]:
e.astype(float)

### np.where()

In [ ]:
a

### convert values > 12 as 1 and values<12 as 0

In [3]:
a = np.arange(1,25).reshape(4,6)
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [4]:
# np.where(condition, return x if True , else y)
np.where(a>12,1,0)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [5]:
np.where(a>12,True,False)

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

In [8]:
# suqare value if its % 5 ==0 (divisible by 5)
np.where(a%5==0,a**2,-a)
# values divisible by 5 => square
# values not divisible by 5=> make them -ve

array([[  0,   0,   0,   0,  25,   0],
       [  0,   0,   0, 100,   0,   0],
       [  0,   0, 225,   0,   0,   0],
       [  0, 400,   0,   0,   0,   0]], dtype=int32)

In [ ]:
np.where(a%5==0,a**2,0)

In [9]:
condition = np.array(['on','off','on','on','off'])
condition

array(['on', 'off', 'on', 'on', 'off'], dtype='<U3')

In [10]:
# Convert on as 1 and off as 0
np.where(condition=='on',1,0)

array([1, 0, 1, 1, 0])

# Splitting of array

In [11]:
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [12]:
#Split an array into multiple sub-arrays as views into `ary`.
np.split(a,2)

[array([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]]),
 array([[13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24]])]

In [16]:
s1,s2,s3,s4 = np.split(a,4)
# unpacking

In [17]:
s1

array([[1, 2, 3, 4, 5, 6]])

In [18]:
s3

array([[13, 14, 15, 16, 17, 18]])

In [19]:
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [20]:
np.split(a,3) # odd distribustion is not allowed

ValueError: array split does not result in an equal division

#### columnwise split

In [21]:
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [22]:
np.split(a,2,axis=1)

[array([[ 1,  2,  3],
        [ 7,  8,  9],
        [13, 14, 15],
        [19, 20, 21]]),
 array([[ 4,  5,  6],
        [10, 11, 12],
        [16, 17, 18],
        [22, 23, 24]])]

In [23]:
a.shape

(4, 6)

In [24]:
np.split(a,3,axis=1)

[array([[ 1,  2],
        [ 7,  8],
        [13, 14],
        [19, 20]]),
 array([[ 3,  4],
        [ 9, 10],
        [15, 16],
        [21, 22]]),
 array([[ 5,  6],
        [11, 12],
        [17, 18],
        [23, 24]])]

In [ ]:
# Assignmentt: np.hsplit(),np.vsplit()

## np.append()

In [25]:
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [26]:
a.ndim

2

In [27]:
#Append values to the end of an array.
# When we have axis=None it will conver n-D array to 1D & add new element's at the end of it
np.append(a,100)

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24, 100])

In [28]:
np.append(a,range(101,106))

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24, 101, 102,
       103, 104, 105])

In [29]:
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [31]:
np.append(a,[-1,-2,-3,-4],axis=1)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

### axis = 1 [for Column]
### axis = 0 [for row]
### axis= None [for 1D array]

In [32]:
# append values  in row
np.append(a,[[-1],[-2],[-3],[-4]],axis=1)

array([[ 1,  2,  3,  4,  5,  6, -1],
       [ 7,  8,  9, 10, 11, 12, -2],
       [13, 14, 15, 16, 17, 18, -3],
       [19, 20, 21, 22, 23, 24, -4]])

In [33]:
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [35]:
#append value in column
# PS: append a row of zero's
np.append(a,[[0,0,0,0,0,0]],axis=0)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [ 0,  0,  0,  0,  0,  0]])

In [37]:
# can we add multiple rows: No
np.append(a,[[0,0,0,0,0,0]],[[2,2,2,2,2,2]],axis=0)

TypeError: _append_dispatcher() got multiple values for argument 'axis'

In [66]:
np.append(a,[[0,0,0,0,0,0],[2,2,2,2,2,2]],axis=0)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [ 0,  0,  0,  0,  0,  0],
       [ 2,  2,  2,  2,  2,  2]])

## np.delet()

In [38]:
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [39]:
a[-1]

array([19, 20, 21, 22, 23, 24])

In [40]:
"""
Signature: np.delete(arr, obj/index, axis=None)
Docstring:
Return a new array with sub-arrays along an axis deleted. For a one
dimensional array, this returns those entries not returned by
"""
# this will remove last element bcz axis=None
np.delete(a,-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23])

In [41]:
# delete last row
np.delete(a,-1,axis=0)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18]])

In [42]:
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [43]:
# delete a last column, but temp.
np.delete(a,-1,axis=1)

array([[ 1,  2,  3,  4,  5],
       [ 7,  8,  9, 10, 11],
       [13, 14, 15, 16, 17],
       [19, 20, 21, 22, 23]])

In [44]:
a # original array is unchanged

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [45]:
# delete a column at index 2,3
np.delete(a,[2,3],axis=1)

array([[ 1,  2,  5,  6],
       [ 7,  8, 11, 12],
       [13, 14, 17, 18],
       [19, 20, 23, 24]])

In [46]:
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [47]:
# remove 2
np.delete(a,1)

array([ 1,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24])

In [48]:
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [49]:
# delete odd numbers from array a
np.delete(a,range(0,24,2))

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

In [50]:
list(range(0,24,2))

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22]

## Convert nD to 1D

In [51]:
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [52]:
a.ndim

2

In [53]:
a.size

24

In [54]:
# reshape
a.reshape(24)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [55]:
# ravel:Return a flattened array.
a.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [56]:
np.ravel(a)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [58]:
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [59]:
# How to convert nD array to 1 D

In [60]:
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [63]:
a[:,[True,False,False,True,True,False]]

array([[ 1,  4,  5],
       [ 7, 10, 11],
       [13, 16, 17],
       [19, 22, 23]])