# Numpy array creation

In [1]:
import numpy as np

## arange()

In [2]:
np.arange(6)
# starts from 0 and stop at num-1

array([0, 1, 2, 3, 4, 5])

In [3]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
#stepping
np.arange(2,21,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

## zeros():array with all zeros

In [5]:
"""
zeros(shape, dtype=float, order='C', *, like=None)

Return a new array of given shape and type, filled with zeros.
"""
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [6]:
# 2D array
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
#3D
np.zeros((3,2,2))

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [8]:
# if i want int zero then
np.zeros((3,2,2),dtype=int)

array([[[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]]])

## ones(): all 1's in array

In [9]:
np.ones(4)

array([1., 1., 1., 1.])

In [10]:
# 2D
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
# 3D

## empty array

In [11]:
np.empty((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
np.empty((2,3,3))

array([[[6.23042070e-307, 3.56043053e-307, 1.60219306e-306],
        [7.56571288e-307, 1.89146896e-307, 1.37961302e-306],
        [1.05699242e-307, 8.01097889e-307, 1.78020169e-306]],

       [[7.56601165e-307, 1.02359984e-306, 1.33510679e-306],
        [2.22522597e-306, 8.01097889e-307, 1.60220800e-306],
        [7.56601165e-307, 2.22522596e-306, 1.42410974e-306]]])

In [13]:
np.empty((2,3,3),dtype=str)

array([[['', '', ''],
        ['', '', ''],
        ['', '', '']],

       [['', '', ''],
        ['', '', ''],
        ['', '', '']]], dtype='<U1')

## full(): supply own value in arrray

In [14]:
#Signature: np.full(shape, fill_value, dtype=None, order='C', *, like=None)
#Docstring:
#Return a new array of given shape and type, filled with `fill_value`.

np.full((3,3),100)

array([[100, 100, 100],
       [100, 100, 100],
       [100, 100, 100]])

In [16]:
np.full(10,-1.2)

array([-1.2, -1.2, -1.2, -1.2, -1.2, -1.2, -1.2, -1.2, -1.2, -1.2])

In [18]:
np.full((3,3),fill_value='Null')

array([['Null', 'Null', 'Null'],
       ['Null', 'Null', 'Null'],
       ['Null', 'Null', 'Null']], dtype='<U4')

## empty():array with garbage values

In [ ]:
np.empty(5)

In [ ]:
#2D

In [ ]:
#3D

## identity(): identity matrix
- diagonal elements 1 and non diagonal 0

In [19]:
# n: means N x N array
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
np.identity(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [22]:
np.identity((2,3),dtype=int)

TypeError: 'tuple' object cannot be interpreted as an integer

## eye(): used to crreate an identity matrix

In [23]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [24]:
#np.identity(n, dtype=None, *, like=None)
#np.eye(N, M=None, k=0, dtype=<class 'float'>)
np.eye(4,6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.]])

In [25]:
#change diagonal position using k
np.eye(4,6,k=3)

array([[0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0.]])

## linspace(): array with linearly spaced values,
- space between 2 consecutive number will be same always

In [ ]:
"""
np.linspace(
    start,
    stop,
    num=50,
    endpoint=True,
    retstep=False,
    dtype=None,
    axis=0,
)
"""
np.linspace(2,10)

In [ ]:
np.linspace(2,10,retstep=True)

In [ ]:
np.linspace(2,10,num=25,retstep=True)

In [ ]:
# dont add endpoint
np.linspace(2,10,num=25,endpoint=False,retstep=True)

In [ ]:
# 
x = np.identity(4)
x

In [ ]:
np.diagonal(x)#gives u an access to diagonal elements

## random(): creates a random number

In [26]:
#random(size=None)
#Return random floats in the half-open interval [0.0, 1.0).
np.random.random(5)

array([0.2287251 , 0.07666987, 0.77394433, 0.83371686, 0.6611736 ])

In [29]:
#2d 
np.random.random((4,5))

array([[0.85312831, 0.42106472, 0.16578744, 0.10512317, 0.73861979],
       [0.33926513, 0.82498131, 0.52810022, 0.02596578, 0.23838235],
       [0.17331457, 0.95660143, 0.6718298 , 0.10647383, 0.54628234],
       [0.76896205, 0.76332014, 0.6116592 , 0.24875108, 0.84496077]])

In [45]:
# random int values
#randint(low, high=None, size=None, dtype=int)
np.random.randint(4,size=12) # when we supply only low then it is exclusive

array([0, 2, 0, 0, 1, 0, 0, 2, 3, 2, 1, 0])

In [49]:
# when we supply both, low and high
#Return random integers from `low` (inclusive) to `high` (exclusive).
np.random.randint(4,12,size=20)

array([10,  4, 11,  9,  6,  8,  7,  5, 11,  4, 10,  7,  5, 10,  5,  7,  7,
       11,  7,  8])

In [51]:
# generate a data of bloodpressure in range 70-120
np.random.randint(70,121,size=50)

array([ 73, 104,  72,  85,  79, 111, 100,  96,  89,  77,  98, 119,  72,
        82,  91, 116,  92,  97,  81, 105, 101, 116,  76,  83,  73, 100,
        71,  71, 112,  70,  78,  76, 116, 116,  70,  95,  73, 110,  94,
       105, 103,  84, 116, 108, 112,  98,  87, 120, 101, 111])

In [52]:
# salary data: 20000,60000 for 100 employees
np.random.randint(20000,60001,100)

array([45938, 20534, 28611, 59190, 28026, 49853, 59319, 57705, 53048,
       37297, 31960, 36462, 39187, 32965, 47414, 37810, 32604, 41126,
       46993, 44975, 34750, 40978, 28387, 20880, 24688, 27596, 40039,
       50665, 36775, 51864, 22331, 35322, 56257, 52121, 58607, 48296,
       39327, 40338, 38222, 58127, 27037, 34134, 52059, 33547, 24558,
       57767, 27941, 43910, 37587, 34231, 28032, 28926, 30179, 45111,
       37740, 40586, 48133, 30817, 20008, 50595, 49073, 53752, 50841,
       25744, 38836, 23700, 57109, 48255, 34928, 56394, 23507, 29821,
       37161, 47784, 29474, 29483, 53518, 56629, 57997, 48603, 40614,
       52650, 36066, 40376, 26176, 23896, 22219, 58376, 22865, 39815,
       31955, 31865, 31984, 27518, 29397, 42923, 59034, 34058, 41185,
       52047])

In [55]:
# if we have array present in memory
# & we need to create a new array with same structure
x = np.random.random((5,3))
x

array([[0.04626334, 0.33499794, 0.65934473],
       [0.52077157, 0.28122627, 0.93756675],
       [0.15224864, 0.96648514, 0.57869996],
       [0.71693607, 0.97960844, 0.06332845],
       [0.00256038, 0.77401378, 0.08219362]])

In [56]:
x.shape

(5, 3)

In [57]:
# create an array of 1's with same shape as that of x
np.ones_like(x)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [58]:
np.ones_like(x,dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [ ]:
# Assignment:
#np.zeros_like()
#np.empty_like()

# Typecasting in numpy

In [59]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
np.arange(10).dtype

dtype('int32')

In [61]:
np.arange(10,dtype=float)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [62]:
np.arange(10,dtype=float).dtype

dtype('float64')

In [ ]:
# 8 bit: 1 Byte
# 32 bit: 4 bytes
# 64 bit: 8 bytes

In [63]:
np.arange(10,dtype=float)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [64]:
np.arange(10,dtype='float16')#in bits

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float16)

In [70]:
np.array(21343,dtype='float16')

array(21340., dtype=float16)

In [71]:
np.arange(10,dtype='f')#default it takes 4 bytes

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

In [72]:
np.arange(10,dtype='f8') #8 bytes

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [73]:
np.arange(10,dtype='i8')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64)

In [76]:
#np.arange(10,dtype=float)
#np.arange(10,dtype='f')
#np.arange(10,dtype='f4')
np.arange(10,dtype=np.int64) # in bits

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64)

In [77]:
np.array([1233223423123,1342134242342342],dtype='i4')

OverflowError: Python int too large to convert to C long

In [ ]:
np.array(123).dtype

## After creation of an array: if we want to typecast

In [78]:
s = np.arange(20)
s

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [79]:
s.dtype

dtype('int32')

## astype()

In [80]:
s.astype('int64')

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19], dtype=int64)

In [81]:
s.astype(object)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19], dtype=object)

In [88]:
s.astype(int)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [89]:
s.astype('i8')

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19], dtype=int64)

In [90]:
s.astype(np.int64)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19], dtype=int64)